### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by mon5termatt** [kyryloren/credential-flooder#1]
**PLEASE MAKE AN OFFICIAL VERSION OF THIS!!!**

this looks awesome, i once made one of these as an autohotkey script but its manually typing username, tabbing to password, then tabbing to submit

**Comment by kyryloren** [comment]
> **PLEASE MAKE AN OFFICIAL VERSION OF THIS!!!**
> 
> this looks awesome, i once made one of these as an autohotkey script but its manually typing username, tabbing to password, then tabbing to submit

i'll add it to my to-do list ;)
